import { motion } from 'framer-motion';
import { Link, useLocation, useNavigate } from 'react-router-dom';
import { useState } from 'react';
import { authApi } from '../services/api';
import { useAuth } from '../context/AuthContext';

export default function Login() {
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [remember, setRemember] = useState(true); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  const { login } = useAuth(); const navigate = useNavigate(); const location = useLocation();
  const submit = async (event) => { event.preventDefault(); setLoading(true); setError(''); try { const result = await authApi.login({ email, password }); login({ email, token: result.data.access_token, remember }); const profile = await authApi.me(); login({ ...profile.data, token: result.data.access_token, remember }); navigate(location.state?.from ?? '/dashboard', { replace: true }); } catch (e) { setError(e?.response?.data?.detail ?? 'Unable to sign in. Check your credentials and try again.'); } finally { setLoading(false); } };
  return <div className="app-shell flex min-h-screen items-center px-4 py-8 sm:px-6"><div className="mx-auto grid w-full max-w-6xl overflow-hidden rounded-[32px] border border-white/10 bg-[#091827]/75 shadow-2xl shadow-slate-950/50 lg:grid-cols-[1.05fr_.95fr]">
    <section className="relative overflow-hidden bg-gradient-to-br from-cyan-400/20 via-teal-400/10 to-transparent p-8 sm:p-12"><div className="absolute -left-16 top-12 h-64 w-64 rounded-full bg-teal-400/15 blur-3xl" /><div className="relative"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-gradient-to-br from-teal-300 to-sky-400 text-xl font-bold text-slate-950">↗</div><p className="mt-10 page-kicker">Market Lens</p><h1 className="page-title max-w-lg">Know the signal. Understand the reason.</h1><p className="page-copy">A focused workspace for stock-trend research, model confidence, and transparent AI explanations.</p><div className="mt-10 grid grid-cols-3 gap-3">{[['8','Symbols'],['3','Signals'],['2','XAI views']].map(([value,label]) => <div key={label} className="rounded-2xl border border-white/10 bg-slate-950/30 p-4"><p className="font-display text-2xl font-bold text-white">{value}</p><p className="mt-1 text-xs text-slate-400">{label}</p></div>)}</div></div></section>
    <motion.form initial={{ opacity: 0, x: 16 }} animate={{ opacity: 1, x: 0 }} onSubmit={submit} className="p-8 sm:p-12"><p className="page-kicker">Secure access</p><h2 className="mt-3 font-display text-3xl font-bold text-white">Welcome back</h2><p className="mt-2 text-sm leading-6 text-slate-400">Sign in to continue to your research workspace.</p><div className="mt-8 space-y-5"><label className="block text-sm font-medium text-slate-300">Email<input className="input-field mt-2" type="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="you@example.com" required /></label><label className="block text-sm font-medium text-slate-300">Password<input className="input-field mt-2" type="password" value={password} onChange={(e) => setPassword(e.target.value)} placeholder="Enter your password" required /></label><label className="flex cursor-pointer items-center gap-3 text-sm text-slate-400"><input type="checkbox" checked={remember} onChange={(e) => setRemember(e.target.checked)} className="h-4 w-4 accent-teal-400" />Keep me signed in</label></div>{error ? <p className="mt-5 rounded-xl border border-rose-400/20 bg-rose-400/10 p-3 text-sm text-rose-100">{error}</p> : null}<button disabled={loading} className="btn-primary mt-7 w-full disabled:opacity-60">{loading ? 'Signing in…' : 'Sign in to workspace'}</button><p className="mt-6 text-center text-sm text-slate-400">New to Market Lens? <Link className="font-semibold text-teal-300 hover:text-teal-200" to="/register">Create an account</Link></p></motion.form>
  </div></div>;
}
