import { motion } from 'framer-motion';
import { Link, useNavigate } from 'react-router-dom';
import { useState } from 'react';
import { useAuth } from '../context/AuthContext';

export default function Register() {
  const [fullName, setFullName] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [remember, setRemember] = useState(true); const [error, setError] = useState(''); const [loading, setLoading] = useState(false); const { registerAndLogin } = useAuth(); const navigate = useNavigate();
  const submit = async (event) => { event.preventDefault(); setLoading(true); setError(''); try { await registerAndLogin({ full_name: fullName, email, password, remember }); navigate('/dashboard', { replace: true }); } catch (e) { setError(e?.response?.data?.detail ?? 'Unable to create your account.'); } finally { setLoading(false); } };
  return <div className="app-shell flex min-h-screen items-center px-4 py-8 sm:px-6"><div className="mx-auto grid w-full max-w-6xl overflow-hidden rounded-[32px] border border-white/10 bg-[#091827]/75 shadow-2xl shadow-slate-950/50 lg:grid-cols-[.9fr_1.1fr]">
    <motion.form initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} onSubmit={submit} className="p-8 sm:p-12"><p className="page-kicker">Create your workspace</p><h1 className="mt-3 font-display text-3xl font-bold text-white">Start researching with clarity.</h1><p className="mt-2 text-sm leading-6 text-slate-400">Your predictions, explanations, and account activity stay in one place.</p><div className="mt-7 grid gap-4"><label className="text-sm font-medium text-slate-300">Full name<input className="input-field mt-2" value={fullName} onChange={(e) => setFullName(e.target.value)} placeholder="Your name" required /></label><label className="text-sm font-medium text-slate-300">Email<input className="input-field mt-2" type="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="you@example.com" required /></label><label className="text-sm font-medium text-slate-300">Password<input className="input-field mt-2" type="password" value={password} onChange={(e) => setPassword(e.target.value)} placeholder="Minimum 8 characters" required /></label><label className="flex items-center gap-3 text-sm text-slate-400"><input type="checkbox" className="h-4 w-4 accent-teal-400" checked={remember} onChange={(e) => setRemember(e.target.checked)} />Keep me signed in</label></div>{error ? <p className="mt-4 rounded-xl border border-rose-400/20 bg-rose-400/10 p-3 text-sm text-rose-100">{error}</p> : null}<button disabled={loading} className="btn-primary mt-7 w-full disabled:opacity-60">{loading ? 'Creating account…' : 'Create account'}</button><p className="mt-6 text-center text-sm text-slate-400">Already registered? <Link className="font-semibold text-teal-300" to="/login">Sign in</Link></p></motion.form>
    <section className="relative overflow-hidden bg-gradient-to-br from-blue-500/20 via-cyan-400/10 to-transparent p-8 sm:p-12"><div className="absolute right-0 top-0 h-72 w-72 rounded-full bg-cyan-300/10 blur-3xl" /><div className="relative"><p className="page-kicker">Built for research</p><h2 className="page-title">Every decision has an evidence trail.</h2><div className="mt-10 space-y-4">{[['Prediction records','Keep each model signal and its confidence.'],['Visual explanations','Inspect SHAP and LIME feature impact.'],['Training activity','Track model runs and their performance.']].map(([title,text], index) => <div key={title} className="flex gap-4 rounded-2xl border border-white/10 bg-slate-950/25 p-5"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-xl bg-teal-300/15 text-sm font-bold text-teal-200">0{index + 1}</span><div><h3 className="font-semibold text-white">{title}</h3><p className="mt-1 text-sm leading-6 text-slate-400">{text}</p></div></div>)}</div></div></section>
  </div></div>;
}
